### ISSUE TITLE
Unswitcher

### ISSUE THREAD

**Issue by antitoxis** [AdKats/AdKats#1003]
I have the problem that adkats just moves me players. They also have a VIP status but this is not taken into account. I only get the two messages from adkats. The multibalancer then tells me that the player has been moved by the admin. But this is triggered by adkats. In the settings I have not set this. What triggers this? Unfortunately I don't see how Adkats moves the player.

[11:03:19 98] [AdKats] MULTIBalancer Unswitcher Disabled
[11:03:20 05] [MULTIbalancer]:2 ADMIN moved player Saufmowas, MULTIbalancer will respect this move
[11:03:20 56] [AdKats] MULTIBalancer Unswitcher Re-Enabled

**Comment by ColColonCleaner** [comment]
What messages are displayed in the chat window when this happens?

**Comment by antitoxis** [comment]
moved by admin.
If i move them in procon, adkats will move them back.
If i disable adkats, it will don't move the player

**Comment by ColColonCleaner** [comment]
Oh you mean you try to move them in the procon player window but AdKats throws them back to the original team they were on? Please use the /fmove or /move commands when moving players around, this is because the 'admin-ness' of a move isn't always included so AdKats doesn't check for it. Basically some of the time when an admin moves a player vs when a player moves themselves can't be distinguised via events alone, so if AdKats believes a player shouldn't have moved themselves it will keep them on their assigned team.
To override this there is /fmove and /move for admins, and /assist for regular players, you can also give players access to move themselves without restriction by giving your vips access to the /moveme command.

**Comment by antitoxis** [comment]
Ah ok I understand. Can I turn it off?
Because I suspect that he always moves players like that. I have these players in the whitlist, but adkats pushes them back and forth anyway.

**Comment by ColColonCleaner** [comment]
If you have these players in a whitelist just enable the /moveme command for them so they can move themselves, then you don't need your admin to do it. 

I just checked and AdKats doesn't respect its own whitelist when a player moves teams via the game without using commands. An oversight on my part.

**Comment by antitoxis** [comment]
The problem is, they're switched first by Adkats. I do not want that. I do everything about the multibalancer. Is it possible to stop adkats from automatically switching players?

**Comment by ColColonCleaner** [comment]
Um. Do you have any of the team power stuff enabled?
https://github.com/AdKats/AdKats#c30-team-power-monitor
Stuff like the unswitcher and join reassignment? That's the only way AdKats will move people without a command being called.

**Comment by mated77** [comment]
Same problem here with server seeders. The Plugin "Balance server seeder" want to move them (so you don´t have 3 of 4 in the same team) MultiBalancer says "Admin moved... will respect this move" and it seems like Adkats blocks it with the message "you are assigned to Team X. Please use assist..." - and then it runs in a circle. Any suggestions how to fix this?

**Comment by ColColonCleaner** [comment]
AdKats has a check for how many moves a player has attempted in the last few seconds and will automatically give up the fight with another script after a little bit.
The 'adminness' of a move doesn't come with the actual player move, it's a separate event that you need to wait for and could come well after the actual player move because battlefield's event system is the best in the land kappa. I never built waiting for that admin event into the system.

One way to solve the seeder issue would be to use the AdKats seeder management, in the team power section. 

Another solution which would be more dirty would be to modify the balance server seeder script to issue movement commands via admin say. For example when it wants to move somebody it would say '/fmove playername' in chat, which would be hidden but acted on by AdKats in the background.

**Comment by mated77** [comment]
Thank you. I will try to figure it out and test it. But did you change something? Today i also get two messages from players complaining about the following situation: they type !assist to help the losing team. Then they get queued to assist and then switched to the losing side and in the same moment they get moved back with the message "you are assigned to team X .. please use assist". So i ask my self is there in issue? Never had this before and i did not change the settings?

**Comment by ColColonCleaner** [comment]
I have not made changes to the plugin in a long time now. If they use assist it performs an admin-move on them from inside the plugin which assigns them to the other team before performing the move.
If you're using assist to control when people can move then i'd suggest turning off the multibalancer restrictions on player movement, just let the team power system in AdKats handle it. I believe there is a setting for it. The two plugins might be fighting with each other.
