### ISSUE TITLE
EXCEPTION-7603-A20.69-D-SendOnlineSoldiers-PlayerListing4

### ISSUE THREAD

**Issue by ghost** [AdKats/AdKats#1005]
im on latest code base 7.x.3
and im getting alot of these errors. My best guess is this is due to non thread safe code? I didn't had the time to investigate but it seems like this is consumer producer issue
[11/22/2019 6:19:51 PM] [AdKats] EXCEPTION-7603-A20.69-D-SendOnlineSoldiers-PlayerListing4: [Error sending online soldiers.][System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at PRoConEvents.AdKats.SendOnlineSoldiers()]

**Comment by ColColonCleaner** [comment]
Yes, back when i wrote the player list management system we ran into issues sometimes where the code deadlocked and at the time I didn't know enough to fix it properly. So instead of having a problem where the code could stop cold I instead made it non-thread-safe, an exception or two can happen rarely but when it does in that thread it will just try again on the next loop through which happens a few seconds later. SendOnlineSoldiers is an interesting place for this to happen though, because I believe that's only used when integrating with the loadout enforcer plugin. How often is this happening?

**Comment by snugglesftw** [comment]
@ColColonCleaner this bug is intermittent (makes sense..luck of the draw for me), but when it happens, it throws exception every 5 min? It was spamming the console + db error log table. look at the image

![image](https://user-images.githubusercontent.com/3228334/69473733-8eb3d280-0d6c-11ea-961d-92880c8cedb9.png)

**Comment by ColColonCleaner** [comment]
Oh really, it gets stuck in this state and never gets out? Are you running the loadout enforcer? If you turn off the loadout enforcer and it disconnects from AdKats do the errors stop once they've started?

**Comment by snugglesftw** [comment]
No LO Enforcer
Running plugins as shown below
So the code deadlocks when you use semaphores or locks?

![image](https://user-images.githubusercontent.com/3228334/69473759-e5211100-0d6c-11ea-80ce-c580e1b2c09a.png)

**Comment by ColColonCleaner** [comment]
It could deadlock yes, and since that was much more debilitating for people using the plugin when it happened (all of a sudden the player list wasn't being updated anymore so commands stopped being able to find players) I removed the locking.
If you aren't running LRT then I don't think there is a reason for that function to be firing, unless there is something I'm not remembering, and that's very likely the case.
I'm very busy this coming week but might be able to look at this after then.

**Comment by Prophet731** [comment]
@ColColonCleaner 

I have LRT running on the BF4 dev server if you want the procon connection info for that.
