### ISSUE TITLE
Spec list is blank when more then 20 ppl

### ISSUE THREAD

**Issue by snugglesftw** [AdKats/AdKats#1012]
Instead of having the code Purge the list if the spec list is greater then 20, can we keep up to 20?

**Comment by ColColonCleaner** [comment]
The server will not allow greater than 20 spectators in the spectator whitelist. So instead of using the server spectator whitelist adkats instead just kicks people who are not in the whitelist when it detects they join spectator. If nobody is in adkats' spectator whitelist then everyone is allowed into spectator.

**Comment by snugglesftw** [comment]
you are right. Just reviewed the code. I figured out why....I had private spec turned on..
