### ISSUE TITLE
Users with "say" permissions can execute other commands not allowed by their role

### ISSUE THREAD

**Issue by redge** [AdKats/AdKats#1024]
We recently appointed an assistant admin, who demonstrated a simple exploit that allows them to execute any Adkats command, including those that fail normally due to insufficient permissions, as long as they have "admin say" permissions.

Simply typing /!say [other command] will cause the command to execute with full permissions. For example:
`/!say !ban ColColonCleaner` will execute the ban.

**Comment by ColColonCleaner** [comment]
@redge There is a setting to disable command execution via admin-say for this reason. It's under the command settings section.
Commands via admin-say is a thing because that's how execution of commands from procon's chat window works, and that executes at the highest possible authorization.
For example you can /ban ColColonCleaner via the procon chat window and it will do that. A / prevents the say from being seen by players.

**Comment by redge** [comment]
Now that you mention it, I do remember seeing that setting.

If my understanding is correct, though, that would remove the ability to send AdKats commands from another plugin such as Proconrulz (which we use). Can AdKats be made context-aware (i.e. if it sees a command in an admin-say that matches a user's "say" command, either ignore it entirely or check that user's role and permissions before executing)?
