### ISSUE TITLE
dps automatic ban [4-rpk74m-86-89-44-103]

### ISSUE THREAD

**Issue by WonderfulFUN** [AdKats/AdKats#1029]
Hello, as stated in the threat topic, this anti cheat tool is not 100% reliable! I have already played Battlefield and the admins of the tool didn't even know what BF3 was, I was one of the official beta testers. So my stats are good! I am also a hardcore player. In hardcore mode the damage is a lot higher than in normal mode! However, the program does not recognize this and you will be banned immediately! Metabans is not an EA approved anti cheat tool for the servers! Even the Metabans homepage does not exist! My name is not found in the Cheat Finder either! This program is more than questionable! And then you read here that you should reduce your stats at BF3 in order to be unbanned ?! Guys what the hell? I think you have no idea about the gameplay in hardcore right ?! With the PKM in HC mode and standing, the thing is so accurate that you can easily do headshots! 2 of my stats are a bit higher one yellow one red that has nothing to do with cheating, that's called skill! And as a beta player, I don't think this anti cheat tool is okay! This tool neither records the life of the opposing player nor whether the server settings are normal or hardcore! Making a program like this is one thing I think is good too ... BUT if you do something like that, then FAIR and properly! Your program bans players who are just better than you! And now, imagine there are better ones than you;) If you do something like that then FAIR as I said. With your tool, it is no longer possible for good players to enjoy the game. Or should I stand up and let myself be shot until you think the stats fit again ?! Think about what you give of yourselves !? In addition, this tool does not recognize server pings etc., which can lead to incorrect information! I was banned with the message AutoAdmin DPS Autobann but DPS as if I didn't even fire a shot finds the error! And again in the HC the DPS of the weapons are higher than in normal mode!

And im sure im not alone with this opinion!

EA support told me that the 3rd party anti cheat tools are not 100% sure so what u say now ?! 

I Dont use Cheats or DPS tools or mods its the failure of your Programm you should fix this of shut it down! 

And i have nothing to hide my ingame Name is M1A2_Wonderful !

**Comment by Hedius** [comment]
Tbh... Yeah MetaBans no longer exists. 
Anyways... Admins can whitelist you or turn the module off.

I wouldn't say that the plugin is outdated, but it's the server admin's decision in the end. Because the weapon metrics are still the same.

@ColColonCleaner probably can tell you more about it's reliability.

**Comment by WonderfulFUN** [comment]
The point is many good players like me who play BF for years have normally better stats than others! And all who use this tool for server Administration should shut this tool down it takes away all the Fun in the game! And the newbies schould make their own servers with special name like noobs only server os smth...

**Comment by ColColonCleaner** [comment]
Explaining the numbers. According to the overall character stats it pulled from the official battlelog site, your character killed 89 players with 103 bullet hits from an rpk74m, 44 of those kills being headshots. The rpk74m deals 25 damage at minimum range, and that can be boosted to 50 damage via headshots. So because your character averaged 86 damage per shot, which according to the numbers is impossible, the script banned your character. Even the best player on earth cannot increase the damage that their weapon deals over the maximum, and over 89 kills, your character's RPK was dealing 172% of it's maximum possible damage. Flagged as a damage mod.

The way around this is to get more kills with the weapon so that the numbers average out to a more normal value, and talk with the admins of the servers where the bans happened to have you whitelisted if that's the path you want to go. Bans from this tool are not global, they are local to the server you're joining, so a ban on one server or server group won't be automatically enforced on others. New bans based on stats will be made if you keep joining other servers running the script though.

**Comment by ColColonCleaner** [comment]
Also a note, the script does handle hardcore servers. Based on the soldier health that the server is configured with (60 health for hardcore servers, 100 health for normal servers) it will calculate the damage per shot based on that value so you shouldn't see a problem joining hardcore servers with legitimately gained statistics.

**Comment by WonderfulFUN** [comment]
And where this program get dmg numbers ?! Your programm is just a fail and EA support says the same ! This irregular Programm banning Players for stats u have in your mind or what ?!  Getting this stats with rpk74m is not hard if u play metro on a 64 players server u get this easy ! As i say i was a Beta player and u come here with ur Programm and dont expect that some players are better than yourself ?! You have no Clue and no dmg numbers the weapons deal ! And i cant play this weapon cause every server who has ur Anti Cheat Tool ban me immediatly just saying now find the mistake ! Ur tool is just a big joke and a fail !
Hardcore work other ways its not only 60% player health the weapon dmg is increased too cause of this its called Hardcore! and u go there and take Dmg numers u have in your mind and say more cant be are u serious ?! If i were cheating or using tool why all my oter weapons dont have these stats too :'D ?! Last time i play this RPK74m was before u release this Anti Cheat tool ! U cant boost 1 weapon only with cheats or mod so just shut down this useless anti cheat programm. EA support told me that this programm is not 100% sure and have many mistakes the reason why is u dont have the Scripts of the puplisher which is EA ur programm is just a fail and u take away the fun of the game for good players thats all your programm is doing !

**Comment by ColColonCleaner** [comment]
Screaming isn't something that is going to help the situation, but there are paths forward. This tool has been around for about 8 years now, and the anti-cheat features about 6 years now. The battlefield 3 damage numbers for weapons are widely available online and have been since release, a quick search and you'll find them yourself. The game has been fully data-mined and unchanged for a long time now.
This script is open source and ran by admins of their own decision because it's respected in the battlefield community, i cannot 'shut it down' even if i wanted to from this end.
If this is in fact due to a glitch in battlelog's stat system then that is indeed unfortunate. Please talk with the admins of the servers you would like to join to get yourself back in the game there. I was an admin of both BF3 and BF4 servers for 6 years and have thousands of hours in both games. If you'd like to review my profiles by all means, feel free.
http://battlelog.battlefield.com/bf3/soldier/ColColonCleaner/stats/448773068/pc/
http://battlelog.battlefield.com/bf4/soldier/ColColonCleaner/stats/448773068/pc/

Also, for your 247fairplay ban appeal here: https://www.247fairplay.com/forum/ban-appeals/ban-appeal-17770/?PHPSESSID=tolpg3aa64nfi0ibdcrb38cvb0
Please look at the stats you linked in that thread and scroll down to your RPK stats. You're 500% over the average. This is the same stat for which AdKats issued the ban against your player.
https://www.247fairplay.com/CheatDetector/M1A2_Wonderful
![image](https://user-images.githubusercontent.com/1903507/102667383-d3b45f00-414e-11eb-8c7c-f6dccba56fff.png)

**Comment by WonderfulFUN** [comment]
Sure thats why EA dont allow ur Anti Cheat tool on BF1 and BF5 Servers :'D gj :'D And i say it again EA told me that my account is totally ok and i dont cheat. And talk to server Admins gj again u cant find the Admins of the servers or talk to them :'D Next point i dont scream i only told you the truth EA says im not cheating and u and your tool say i do... whos right there you or the Publisher ?!
I play this gun 35 min and never touch it again cause i unlock the next weapon in just 1 round. It was on a 64 players server with Map metro but its ok players like u who call urself Colonel are the best and noone can be better :'D if someone is better they cheat :'D

And by the way i fired 1512 rounds with 89 kills and 44 HS yea thats cheating xD  if i cheated i would have like 1000 Kills and 500HS :'D But yout tool knows all youre just a bad Programmer and u cant accept some players are Better than u ! This useless tool only compares kills and HS but it dont count the rounds (Bullets) fired with this gun better shut ur useless Programm down rework ita and bring it back again !
