### ISSUE TITLE
Clock change bug KPM automatic bans

### ISSUE THREAD

**Issue by CheckaWiemi** [AdKats/AdKats#1045]
As clock has changed this night nearly all of our players got banned with the reason: "KPM Automatic Ban [LIVE][5-L25-42]"
I guess it is just a bug and needs to be fixed until the European Union finally abolishes the time change

**Comment by Hedius** [comment]
The kpm logic uses local time.

This bug has been around for a long time.
The easiest fix is to disable the anti cheating module short before the switch or set the time zone to UTC.

That's what I did.

The fix itself is not that complicated.

The low level and high level kpm checks need an update to use UTC instead of local time.

The logging off the kills probably also needs to be updated to UTC.

**Comment by Hedius** [comment]
Also for context this is not a EU specific problem. Most countries use a daylight saving time.

The main problem here is that hosters like g-portal or others run their servers with local time instead of UTC.
