### ISSUE TITLE
Optimisation

### ISSUE THREAD

**Issue by Maximsiv1410** [AdKats/AdKats#1046]
Hey, nice work.
But as bf4 fan and a mature software engineer I couldn't resist to review your source code...(it's in my nature)
So here what i have to tell you:
1. Consider refactoring your project in order to reduce memory consumption and unwanted overhead of using so many threads. At least for the beginning you could use thread pool and tasks just to limit unneccessary allocations in a hotpath.
1.1 Why you dont use asynchronous approach in this project architecture?
It could drastically improve your app performance and as well. I really advise you to think about it, because i often see high latency of plugins response.
What's more, since in fact your app dont need being as RAPID as High-Frequency Trading systems are, you could use async approach in order to increase throughput(bandwidth) and at least eliminate blocking IO(which in fact is a perf-killer in your case)
2. No offense, but.. seriously, 65k lines of code in a single file? :D
3. There are lots of other nags, but they are just about small optimisations, data consistency and code style, which are parts of engineer principles, so they are not so important for this project

**Comment by Hedius** [comment]
1. This project is not maintained anymore.
2. PRoCon plugins are meant to be single file plugins :) Blame PRoCon for that :)

**Comment by ColColonCleaner** [comment]
Keep in mind this was created while I was a newly in college. 

1. A rework/redesign was planned and started but DICE dropped support for RCON so I lost interest many years ago. The threads are mainly there in the first place to avoid bogging down the main procon thread since it's tied to the UI. When this was built we were locked into .NET 3.5 which came with its own limitations, the upgrade for .NET to 4.6 came well after support for this project ended. Generally response times are more limited by the latency to the database rather than lag in the code/threads, however I will say you're spot on by saying memory management could be improved.
2. Procon pulls in plugins via a single file. You can get past this with .inc files but then code highlighting and such doesn't work with IDEs so I stuck with a single file.
3. Again, coded while I was still in college. Looking back at this a lot could be improved, and that comes with the territory when you're many years into software engineering as a profession.

**Comment by Maximsiv1410** [comment]
Oops, I didnt notice it's no more maintained! :)
I know that hardware often solves a problem of performance, but i just could pass by since im a performance addict
Well, yet it was a pleasure to have your answers so fast, guys
Sorry for bothering, wish you all the best! :)

**Comment by ColColonCleaner** [comment]
All good, it's nice to reminisce about old times.

**Comment by Hedius** [comment]
Well BF4 is still alive :) Gotta stick to the last decent Battlefield title with RCON / rental servers... :)

**Comment by ColColonCleaner** [comment]
Yeah, I'll probably open it back up at some point for a night if I get a chance with everything else going on.

@Maximsiv1410 It's still maintained in part by the community now, just not directly by me anymore. @Prophet731 usually handles that along with PRs from others, as he's built a hosting service for it. If there are bugs found they are usually fixed that way, but overarching changes to architecture are not likely to happen at this point. In general it's good enough for what people need and is still miles above other methods of admining BF servers in terms of feature set, which is one of the reasons the replacement/rework was canned since that was easily another 1000 hours of work.
