### ISSUE TITLE
false DPS ban

### ISSUE THREAD

**Issue by 00050** [AdKats/AdKats#1047]
Good day! I want to report a false DPS ban.
Yesterday I was blocked on three servers by your AdKats tool.
I wouldn't post here if I was only blocked on one server. Three servers banned me. Perhaps even more, I did not dare to check and go to other servers.
Reason: DPS BAN [4-QSZ92-42-1248-128-2934]
I spent all day today trying to figure out what happened.
As it turned out, I made too many kills with a small number of hits.
And there is a simple explanation for this.
I've been playing a lot on the Sniper Only server lately and used a pistol to finish off an opponent after firing a sniper rifle. Accordingly, two or three shots were enough for me to finish off the enemy.
How it looks like (these are my clips):
https://clips.twitch.tv/SpineyDistinctRavenStoneLightning-6KIAPUhXIHEQvgFx
https://clips.twitch.tv/HandsomeEphemeralPorcupineMikeHogu-CBoIBXCYcYm3nFjY
https://clips.twitch.tv/DrabStrangeCurlewFUNgineer-QrJm48nCXctDxm-O
https://clips.twitch.tv/LachrymoseDeadWalrusKAPOW-iJzaaUQAighNPUnL

Take a look at my statistics: https://www.247fairplay.com/CheatDetector/fluffy-pony-tail
If you sort the table by K/H you will see that I have similar stats on most high RPM pistols because I used them in the same way:
SW90: 65.38% Kills/Hits
M1911: 50.72% Kills/Hits
CZ75: 43.4% Kills/Hits
QSZ-92: 42.76% Kills / Hits (which is 260% above average, which led to the ban)

Most likely, my report will lead to nothing, but I wanted to let you know that such a situation can occur.

Sad situation. I will spend the rest of the day justifying myself to the administration of these servers and begging for an unban.
If I fail to get unbanned, then most likely I will delete the game. After spending five hundred hours trying to learn how to play it.

Thank you for your time.

**Comment by Hedius** [comment]
Hi,

observed your messages in the BF4DB discord.

You can ask server admins for an anti cheat whitelist. This prevents Adkats from banning you.

Another solution would be to lower your stats for the affected weapons.

It's not really possible to automatically detect your play style.

Your stats are impossible to reach if you would only use those weapons.

But you exploit the system by switching weapons everytime.

This lowers the stats for your sniper rifles and raises them for pistols.

It is not possible to detect that your are dealing 75% damage with a rifle and 25% with the pistol.

So the only solution on the plugin side would be to modify the allowed damage ranges for pistols. This would prevent your case from triggering. However, also would break the normal detection for single weapon kills. 

Therefore, it would be a really bad idea to modify the allowed weapon stats. Since it works totally fine in most cases. Except your edge case.


Most servers use AdKats. You will trigger a ban on all those servers if they have the anti cheat module enabled.

Each server will have to whitelist you. But this discussion and the discussion on the BF4DB discord should be enough to achieve this.

**Comment by 00050** [comment]
> But you exploit the system by switching weapons everytime.
> This lowers the stats for your sniper rifles and raises them for pistols.

Good to know! I didn't know about that mechanic. Gonna replace pistol with knife instead in that case. 
Thank you for your answer!

**Comment by 00050** [comment]
Today I got another false ban for KPM.... Great tool.
