### ISSUE TITLE
Multiserver-Support?

### ISSUE THREAD

**Issue by fak0r** [AdKats/AdKats#367]
Are there any plans for Multiserver support? Users grouped by ServerID, Bans grouped by ServerID. Just everything grouped by ServerID.
The current system is good for clans with many servers. For RSP's less :)
Currently, all users would distribute to all servers as we use only one database for all servers.

**Comment by mpoonuru** [comment]
I have a question My Friends! I have two servers! Can I use single database for both the servers? Do I have to add all my first server Admin details in the second Server Adkats plugin? 

How can I use single database for both my servers? How to configure the Adkats plugins? Could you please help me?

**Comment by ColColonCleaner** [comment]
@mpoonuru Just connect your second layer to the same database, once stat logger has loaded that server into the database adkats will also have all your admins/users from all servers in the that database. The whole point of AdKats was to have multiple servers on a single database :+1:

**Comment by mpoonuru** [comment]
Hi Friend, 

OMFG, You responded so quickly?Thank you. So I have to add stats logger and Adkats plugins in the Second Procon Layer and update the database details? That's it? It will take care of the rest?

Bro, if you can help me, I will donate you bro! Please! How we can communicate?

**Comment by ColColonCleaner** [comment]
@mpoonuru Yes, just add the plugins to the second layer just like you did the first, and use the exact same database credentials. Basically do the same setup steps as before. The plugins will handle the rest and you will see your users/admins in both servers. Any changes you make to users/admins will be pushed to all servers at 5 minute intervals.

**Comment by mpoonuru** [comment]
Hey Bro,

I would like to work with you on this! If you can help me, please I will donate you right away! I want to talk to you!

**Comment by mpoonuru** [comment]
Thank you Bro, I will do it and let you know, If I run into issues. I tried BFAdminCP which is not working at all for my servers. :( I tried to reach prophet on ADk Gamers still no response. I don't know whom to contact for the support.

**Comment by ColColonCleaner** [comment]
@mpoonuru Both myself and @Prophet731 have dropped support for AdKats and the BFAdminCP respectively. We still offer help over text sometimes when we can, but support for these systems has officially ended as we've moved on to other things. About 4000 hours of work on this plugin was enough for me.

**Comment by mpoonuru** [comment]
@ColColonCleaner  LOL bro, I just started here!  I work for ORACLE Corporation! Whenever I get time, I play. So thought of having BF4 servers and started those. That's really nice still you guys are helping us whenever 
you get time. I am damn lucky today to get response from you. Can you please share me your donation site, I would like to donate some! 

I have a question bro, When I was trying to change the role settings the list is moving up when I change the value and it's irritating how to handle that? Could you please let me know, if you have some time?

**Comment by ColColonCleaner** [comment]
The main plugin thread: https://forum.myrcon.com/showthread.php?6045-FREE-Advanced-In-Game-Admin-and-Ban-Enforcer-AdKats-6-9-0-0

The link is at the bottom of the first post. I'll link it here though. Thank you for the contribution.

https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=danielgradinjan%40gmail%2ecom&lc=US&item_name=AdKats%20-%20Advanced%20In-Game%20Admin%20for%20Procon%20Frostbite%20-%20Donation&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted

As for your role setting behavior, this is an unfortunate problem with Procon's setting generation script and I can't fix it. Every time something is changed I need to re-generate the setting list, and since text changes so users understand better, procon thinks its new settings and throws you back to the top of the list. 

I did add something to help with this though. There is a setting section selector at the top of the setting list. Use that to move around to only the setting section you currently want to be editing, it makes the re-generation/scrolling both quicker and less irritating. Tried to do what I could with what was given me for a UI.

AdKats at some point had a vision of separating from procon, but the fact was that too many people used procon to make switching away from it viable. Procon is popular because people use it, and they use it because it's popular, etc, etc. It's not the best, but it does the job, awkwardly at times, but it does.

**Comment by mpoonuru** [comment]
@ColColonCleaner  I just donated some! You guys are awesome doing a great Social work here for the players. I bought ios app procon also. 

That's true. people use Procon that's why it's famous. Keep in touch my friend! I will contact you if I run into issues as I will be setting up the another procon layer in a few moments.

I was using two databases for two servers because when I added the same database details, I ran into many issues, I was maintaining two databases. Now I will try as you said and let you know. If this is successful it will be a hassle free job for me. I don't get much time to manage my servers as I am busy with my office work. It was really difficult for me to handle both servers. But if this works well, I can sleep well.

**Comment by ColColonCleaner** [comment]
@mpoonuru Thanks for the contribution!

The most I've seen being used on the same database is 30 servers, don't remember the clan running it. The most we personally had on a single database was 13. Two is no issue at all for the plugin to handle. Cheers.

**Comment by mpoonuru** [comment]
@ColColonCleaner Oh! Super. 
So here are the steps I have to follow on the new procon layer:
1. Copy XP Stats Plugin --- Add Datbase details, if it is running fine, shutdown procon
2. Add Adkats plugin file --- Start procon layer, Add only database details that's it?

**Comment by ColColonCleaner** [comment]
@mpoonuru Yep that's it, shortly after loading up you'll see all your users/admins from the other server on the new one.

**Comment by mpoonuru** [comment]
@ColColonCleaner Awesome bro! Thanks a lot! Keep in touch! I sent you a Linked in Request! you can find my name there! thank you.

**Comment by Prophet731** [comment]
@mpoonuru 

What was the problem you were having with the BFACP? As @ColColonCleaner said we really don't work on these anymore and we've both been very busy.

**Comment by mpoonuru** [comment]
@Prophet731 How are you doing bro? Nice to talk to you! It never loadsup, Java script load error, Unable to contact the server. Many issues my friend! I am struggling a lot to contact you. Then I dropped that . will you be able to help me my friend?

I love the WEB UI. You made it awesome my friend. Advanced Robotics ;) Which Branch your want me to checkout? I see that you are working on a latest update. Please do let me know my  friend.  https://admin.corehqservers.com is the one I am going to use it for BFCPAdmin. I will donate you bro, if you can help me. 

default  username password was not getting created on the DB. java script always failed to load. when I use server.php directly it loads the Server settings but nothing works.

**Comment by Prophet731** [comment]
I'm at work right now so when I get home I'll be able to help you. It will be a few hours though. First question though do you have shell access to your web server? That will help out a lot if you do.

**Comment by mpoonuru** [comment]
Hi Prophet bro,

I don't have shell access to my Web Server.  :(. I am working from home today. I have some time to check. Please do let me know dude when you are home, so that we can use team viewer to access my system.

**Comment by mpoonuru** [comment]
@Prophet731 Hi Bro,

Do I have to update the permissions for the sql files also in app/storage folder to 0777?
[https://admin.corehqservers.com/bfadmincp](url) 

I haven't run this. Waiting for you to run this for the first time, so that you can easily fix this.

**Comment by mpoonuru** [comment]
@Prophet731 I am eagerly waiting for you bro. Please do help me!

**Comment by mpoonuru** [comment]
@Prophet731 Hi Bro,
I ran this unfortunately by accessing the url and it gives me an error: Error in exception handler.

**Comment by Prophet731** [comment]
Alright well i'm home, exhausted though. Let's continue this discussion over here so we're not spamming this ticket.

https://github.com/Prophet731/BFAdminCP/issues/250
