### ISSUE TITLE
REQUEST: Add a command to view BF4DB player cheatscore in-game

### ISSUE THREAD

**Issue by jamesonp** [AdKats/AdKats#534]
It would be awesome if there was a command to check a players BF4DB cheatscore in game with a command.  I believe the API is there since ADK Web Admin has the ability to pull the score.

**Comment by ColColonCleaner** [comment]
We do not use BF4DB features internally, but it could be added via command.

All future requests for features that are not internally used/generated are by donation only, and will be completed within a week of acceptance/payment. A new system is being developed that will eventually replace AdKats, and focus needs to be placed there. Cheers!

**Comment by antivanity** [comment]
- enabled/disable local ban by: (1) bf4db stats ban, (2) glitching, and/or (3) padding
- option to log all on bf4db nonzero cheatometer scores, resulting in a suspicious-players list to a database table. Log name, link to bf4db profile, cheato score.
- option to set a threshold on the cheato score and execute a command. IE: Anything over 35% cheato score, issue a custom command: !bb 120 %playername 8

Name your price. Lets get this done! Thanks CCC

**Comment by f0nt4** [comment]
+1 on antivanity
Most wanted is an automatic kick when someone is banned on bf4db for hacking/cheating.
But that might involve a lot of traffic to the bf4db site, and we don't want to ddos it.
So it would be nice if the player would get a local ban.

**Comment by ColColonCleaner** [comment]
It would be a bad practice to automatically ban someone because they are banned on BF4DB. That would require the banned player to dispute their ban in both places if BF4DB unbans them.

New code to fetch BF4DB info for all players entering the server.
Updates to BF4DB info at the end of each round they are in the server.
Logging all suspicious stats noted about the player.
New command to view cheatscore on BF4DB.
New command to whitelist a player from kicks by BF4DB enforcement.
New command to unwhitelist a player from kicks by BF4DB enforcement.
New settings for:
Enforce By Hacking (Kick Message: BF4DB Banned for Hacking)
Enforce By Gliching (Kick Message: BF4DB Banned for Glitching)
Enforce By Padding (Kick Message: BF4DB Banned for Stat Padding)
Option to log suspicious stats
Level of cheatscore to trigger logging
Option to auto-action by cheatscore
Level of cheatscore to trigger action (minimum 25%)
Action selection (kick, ban), message 'BF4DB CheatScore X"

What should be changed?

**Comment by antivanity** [comment]
Do you have an API for bf4db that returns more information than just cheatscore ? Or are you going to be scraping the data off of the page ?

**Comment by Prophet731** [comment]
As far as I know, the API they provide doesn't provide more information, however, it does return their cheatscore and their BF4DB ID. The BFACP actually hits that URL to get their cheatscore currently.

**Comment by f0nt4** [comment]
Don't know if the "Updates to BF4DB info at the end of each round they are in the server." are neccesary.
Maybe it's better to call an update on an player when it enters the server and after that request the cheatscore and pick the ban status if any from the site.
The api doesnt return the ban status, but does return some other stuff:
Like this guy, banned but doesn't show up in de returned data:
http://api.bf4db.com/api-player.php?format=json&name=shadowfox1900&guid=
Returns:
{"type":"success","message":"OK","data":{"bf4db_url":"http:\/\/bf4db.com\/players\/15230704","personaName":"shadowfox1900","cheatscore":80,"rank":42}}

**Comment by ColColonCleaner** [comment]
We need to contact them about adding ban status and reason to their API.

**Comment by f0nt4** [comment]
I'm wondering if he's willing to do that. 
Because the one behind bf4db, is the same person as behind bfrcon.

**Comment by ColColonCleaner** [comment]
BF4DB is a public service, shouldn't be an issue. Someone please contact them and direct the inquiry here.

**Comment by Christian1998** [comment]
Any news here after one year? The feature would be great on BFH too ;)

Regards
