### ISSUE TITLE
Suggestion: Cross-server player-interactive command issuing

### ISSUE THREAD

**Issue by iraqiboy90** [AdKats/AdKats#724]
Hello

Would be better with the combination of the following:
- !report / !admin commands issued by players will send a notice to other admins on other servers

So what do you think about cross-server command issuing?
example: Someone reports someone for something on another server. I, on another server gets a notification with who reported who for what. 
I then decide to ignore/accept/deny the report, or act upon it with the report ID.

**Comment by ColColonCleaner** [comment]
This is actually two tickets.

Report IDs are not unique outside of a single round on a single server, so that would need to be changed to a global listing of reports. Perhaps a new table. So the report system would require an overhaul.

Secondly, the command system would need to be restructured to be server ambiguous, and all commands with player targeting would need to search through all online players in your servers for a viable match. Would probably need to add more information to the find command on players not in the server because that info isn't available otherwise. Another overhaul.

Both of these could be internally used, so i'll look into it for future usage.

**Comment by iraqiboy90** [comment]
:+1:
