### ISSUE TITLE
REQUEST: Customizable command whitelist and respective commands

### ISSUE THREAD

**Issue by antivanity** [AdKats/AdKats#741]
Ability to add users to a list that is protected against commands.

Would make sense to have a new section to create a list of users, then add a list of commands to protect against.

Where/How do i donate for this feature ?

Thanks CCC!

**Comment by ColColonCleaner** [comment]
This is along the same lines as #738, the difference is this would apply to admin commands rather than report/calladmin which are for the most part public commands. Go over the command list and state which commands should be included in this whitelist. Assuming you want things like punish/kick/ban etc, but list any others that should be included.

Two new commands and a new special player group would be required for this. I'll make it the same donation amount as #738 as it's about the same amount of work. Send $10 to the AdKats donation link, reply with which admin commands should be blocked on the target player, and I'll add it.

All future requests for features that are not used/generated by ADK are by donation only, and will be completed within a week of acceptance/payment. A new system is being developed that will eventually replace AdKats, so focus needs to be placed there. Cheers!

**Comment by antivanity** [comment]
Our main issue is we have some public players that are really good. And our admins keep temp-banning them for review for our security staff. We might want to protect them from !pp as well.. not sure yet.

Not sure why you want to hardcode a list of commands for this feature ? I was thinking more along the lines of 2 arrays;

first array is a list of users ('user1', 'user2')
second array is a list of commands ('!pp', '!bb')

Im will to donate $50 for the 2 array method. Would that cover it ?

**Comment by ColColonCleaner** [comment]
Not that I wanted it hard coded, you just didn't say you wanted it customizable. Adding options are definitely doable. I can add a list editor for the different commands that this whitelist would apply to, you will be able to enter them by command text. Yes that donation amount is fine.

**Comment by antivanity** [comment]
Donation made, confirmation #9CJ41187R7492445U

**Comment by ColColonCleaner** [comment]
Funded. Feature will be completed within a week.

**Comment by iraqiboy90** [comment]
isnt this similar to this? https://github.com/AdKats/AdKats/issues/721

**Comment by ColColonCleaner** [comment]
#721 is role specific, this is player specific. Details for that request still need to be fleshed out.

**Comment by ColColonCleaner** [comment]
Final stages on this one.

**Comment by ColColonCleaner** [comment]
Patch added. Testing.

**Comment by ColColonCleaner** [comment]
Patch complete. List of commands can be added under command settings. Commands to give or remove command whitelist are /cwhitelist and /uncwhitelist respectively.

**Comment by antivanity** [comment]
thanks, ill check it out shortly.
