### ISSUE TITLE
DPS dont work as it should

### ISSUE THREAD

**Issue by TheMightyCrown** [AdKats/AdKats#799]
Hello,
the DPS automatic ban didn't work as it should.
So me and my friend, we were playing on a two player server, just to lern the maps, having fun etc.

The end of the song was, that I get banned from a lot of servers because of this DPS automatic ban now.

What can I do now? can anybody help me?

Please check out my profil: 
TheMightyCrown 
on BF4 and my Platoon.

Sry for my worse englisch and many thanks for the help!

J.B.

**Comment by ColColonCleaner** [comment]
Please contact the admin owning the server which banned you and send me the full ban reason. You cannot see the full ban reason on battlelog.

**Comment by TheMightyCrown** [comment]
I got in touch with the admin, but the dps automatic ban comes again and again.

Reason is;
DPS Automatic Ban [G36C-540-81-46]

The server is my "home"-server - the server of my clan.
As you can see, we have really great gamer in our clan - as well as the 5th best tankdriver of the world.

So what can I do? Is it possible to clean the automatic ban? or is it possible to reset the something? maybe the stats which the dps automatic ban is using?

It is a cruel that I allways a an admin to reset the automatic ban to play till it runs the next round.

If I had know how many problems I got for an evening of fun, I neve would do that again.

Many thanks for your help!
J.B.

**Comment by TheMightyCrown** [comment]
Can you tell how we can update the data bank of the cheating player list?
Maybe this is the problem. Also with an unupdated MetaBan list.

Here are two links:
http://bf4db.com/players?name=TheMightyCrown
http://i-stats.net/index.php?action=pcheck&player=TheMightyCrown&game=BF4&sub=Check+Player

Many thanks,

j.b.

**Comment by ColColonCleaner** [comment]
The DPS system banned you because according to your battlelog stats your G36C is dealing 540 damage per shot.

Go to your BF4DB page, click all weapons, then scroll down to the G36C, you'll see this: 
https://i.gyazo.com/9d10c764b0063834811fc922a5c8325b.png

The plugin acted correctly based on the stats battlelog provided. If these stats are incorrect that is on battlelog, not this plugin. 81 kills in 15 hits sounds like something went wrong on their end with logging stats though, not a damage mod. I'll add a catch for things like this, but you should work on fixing your stats so this doesn't happen with other anti-cheat plugins, mine is not the only one.

**Comment by ColColonCleaner** [comment]
The DPS system banned you because according to your battlelog stats your G36C was dealing 540 damage per shot.

Go to your BF4DB page, click all weapons, then scroll down to the G36C, you'll see this: 
https://i.gyazo.com/9d10c764b0063834811fc922a5c8325b.png

Actually now it's 571 damage per shot, with 58% headshot/kill, which is highly suspicious.

The plugin acted correctly based on the stats battlelog provided. If these stats are incorrect that is on battlelog/battlefield, not this plugin.

**Comment by TheMightyCrown** [comment]
Thank you again.
"Either boosting or a damage mod would cause this" - but I haven't use something like that.
Can you tell me who I can contact to make the stats correct?

Many thanks!

J.B.

**Comment by ColColonCleaner** [comment]
You only have 81 kills with G36C, so i would suggest looking back and finding the reports that gave you those kills. Link them here and I'll look them over.

**Comment by TheMightyCrown** [comment]
Hey ColColonCleaner,

is it possible to get in touch with you on a "privat" ( not public ) way via Battlelog, Team Speak or Email?
I know my english is very worse and, especially when it gets complicated, I can't explain what I want to say. So people missunderstand me sooo much.

Many thanks,

J.
