### ISSUE TITLE
Metabans propagate filter on AdKats

### ISSUE THREAD

**Issue by Subman-CNP** [AdKats/AdKats#803]
It would be useful to have an option to enter a list of a ban filters for metabans on AdKats, so that ban will be propagated to metabans only when admin will provide some specific reason (eg. cheating)

**Comment by wizard45** [comment]
I agree.

Sometimes we ban people for clan policy violations that do not merit having the ban player put on our metabans list.

**Comment by wizard45** [comment]
Any update on this request?

**Comment by ColColonCleaner** [comment]
https://forum.myrcon.com/showthread.php?6045-Advanced-In-Game-Admin-and-Ban-Enforcer-AdKats-6-8-0-0&p=125938&viewfull=1#post125938

**Comment by ColColonCleaner** [comment]
Funded for completion within 1 week.

**Comment by wizard45** [comment]
Hello,

Any update on this project?

**Comment by ColColonCleaner** [comment]
One week has not elapsed. Initial version of this feature will be completed before then.

**Comment by ColColonCleaner** [comment]
This feature is added in 6.8.0.13, let me know how it goes.

There is a new setting called 'Metabans Filter Strings'. Add filter strings one per line.

If that filter list is not empty it will only submit bans to metabans that include any of the given filter strings in the ban reason. The check is case-insensitive i.e. ignoring capital/lowercase differences.

If the filter list is empty all bans are submitted to metabans.

**Comment by wizard45** [comment]
Thank you for your efforts.  All of our server have been down for the last 3 1/2 days due to server provider hardware issues.  Our servers are up and running at this time.  I believe I understand what I need to do now to get only the bans I want to be submitted to metabans.

I have one question about how to submit one type of bans. How do I list the bans from Adkats from the HSK Checker, KPM Checker, and DPS Checker.  I want these bans to be submitted to metabans and I am not sure how I should list them in the filter list.

Thank you for your time in creating this feature for me and taking the time to answer my questions.  I know your busy and must not have much time to do anything else with all the questions and problems submitted to you!
