### ISSUE TITLE
DPS Automatic Ban [M416-64-75-8]

### ISSUE THREAD

**Issue by Th1agones** [AdKats/AdKats#860]
I started playing with this weapon to unlock all weapon attachments. But i received the following message:

DPS Automatic Ban [M416-64-75-8]

The server admin removed my ban and said i got this ban because my M416 was making more damage as usual. How this autoban works? I never used any hack.

This experience is discouraging me to release new weapons/attachments.

My battlelog: http://battlelog.battlefield.com/bf4/soldier/Th1agones/stats/382848242/pc/
I was banned when this game ended: http://battlelog.battlefield.com/bf4/battlereport/show/1/691380583557067072/382848242/

Thanks.

**Comment by CapeCod** [comment]
I have been fighting with this for well over a month now. Same gun too! I'm am also a clean player. The headache this has cause is beyond words. Since I have been banned on 4-5 servers I now have to try to plead my case with every server clan I have been banned from so they will add me to there white list. It hasn't turn out so well. I'm still banned from most because of this autoban (DPS) program which has completely ruined my gaming experience playing BF 4.

Good luck hope everything works out for ya because it hasn't here. :(

**Comment by ColColonCleaner** [comment]
It was actually due to the previous round, Th1agones.

This one: http://battlelog.battlefield.com/bf4/battlereport/show/1/691377421748105536/382848242/

According to that report you got 48 kills with the M416 but only 52 total shots hit. That calculates out to 92 damage per shot (55.3 damage on hardcore), nearly 1-shot-kill across 48 kills. 

If you are truly clean the best thing I can say to do is to get a lot more kills with that weapon using normal damage. It will bring the overall damage down on it so the system won't trigger on you anymore.

**Comment by Th1agones** [comment]
Thanks for the attention and the explanation. 

I really think its impossible get 48 kill on 52 shots, so maybe its an statistcs problem. I don´t know how many headshots i´ve made but i think the only way to kill with a single shot, even on hardcore, it´s by an HS.

And my accuracy at the game was 18%, so considering the 320 HE multikills (metro map) i´ve shoted a minimum of 394 bullets.

Maybe when I changed the attachment (reflex) the program started counting my shots again and in the end it considered all my kills with the weapon? 

Anyway, i think the program consider basic statistics, disregarding the assists given by other players, 60 Hitpoints on hardcore, etc. So its very rash to ban someone on a single outlier statistic. As a clean player i consider this humiliating. I´m not desconsidering the great work you guys do, but i think this dps autoban should be revised.

Thank you for your attention.

**Comment by ColColonCleaner** [comment]
Yes it is impossible to get those stats, without a damage mod, or apparently this very rare statistics glitch with battlelog. The system acts based on overall stats with a weapon, and a 50 kill minimum.

Since battlelog appears to have these glitches very rarely on its round stats it may be good to increase the minimum kill count for a weapon before triggering on players with a large amount of playtime hours.

Increasing it to 200 minimum kills on a weapon for players with over 300 hours should be sufficient to stop this from happening.

Apologies for the strife this has caused, it's difficult to have 100% detection without false positives, especially when the data provided can in quite rare cases be faulty.

**Comment by regulator174** [comment]
@ColColonCleaner , I am an admin for our Clan DirtyGuns (DGNS), and I'm trying to resolve @CapeCod DPS ban. Can you please help me get the whitelist for hacker check set up. I'm really new to changing stuff around in AdKats and don't want to screw anything up. I see that there is a whitelist function, im just having trouble locating where the list is. Any help would be greatly appreciated. CapCod has been a member and longtime friend of our group and at the moment can't even play on his on clan's server.

**Comment by ColColonCleaner** [comment]
@regulator174 There is a default command for whitelisting players in the hacker-checker.

!hcwhitelist perm CapeCod

perm means it will issue a permanent whitelist.

I thought I already mentioned that command in cape's previous issue.

**Comment by regulator174** [comment]
You did, I was confused as to where to put that, do I also have to set user role to "Allow" hackerchecker whitelist in order for this to work?

**Comment by ColColonCleaner** [comment]
You can issue any command from the procon chat tab, just use a / in front of it.

so /hcwhitelist perm capecod

Or yes you will need to enable that command on your admin role.

**Comment by regulator174** [comment]
Thank you that seemed to work, says he's now on the whitelist. I noticed that I have a command error. This is probably from messing with stuff earlier. Any idea what this is?
[15:21:43 01] [AdKats] ERROR-6810: [Command  not found, removing from command target whitelist commands.]

**Comment by ColColonCleaner** [comment]
Yeah, command target whitelist is something completely different. There is a settings section of the docs where you can find what each setting means.

**Comment by regulator174** [comment]
Im guessing i turned something on i shouldn't have. I'll keep digging. Thank you for you patience Col. yes I'm noob.

**Comment by StNr** [comment]
These checks are a god send for admins.  A clean player is more likely to appeal a ban and any decent admin will look over ALL stats then and come to an informed decision.  

Yes it might give out some false positives (nothing is ever perfect) but it stops alot of the blatant cheaters dead in their trackers.

**Comment by Galenta** [comment]
Hi. I've done something really stupid. I discovered I got banned for having a high kill ratio over time. To explain, I wanted to get a dogtags for owning pistols, specifically G18 and G18 with silencer. I found a srvers "mage no kill" and "Vigilantes Unlock Server" suitable for this. There I got help from people with the same goals and we trade kills. all this happened in a short time. but I managed to extinguish those stats. Now my kill per time ratio is back to normal. but the auto-admin still won't let me on 90% of the servers. In 11 years of playing BF3 I have never used cheats. but sometimes I use the servers of unlock assignments. My account is over 12 years old. I've never had any other accounts. Very sad if my Battlefield journey ends like this. (or I'm gonna have to start a new account.😭)

I contacted Fairplay, but they don't give me any answers.....

I contacted cheatcatchersguildguild.guildtag.com ( https://cheatcatchersguild.guildtag.com/forum-thread/auto-admin-kick-permanent/331170/) and they whitelisted me. And I was given access to Banana Republic. 
 

In Battlefield 4, I did the assignments as well. And you can see my silly red values there.

I'll be lowering suspicious stats there, too.

Fairplay hasn't been updated for over 2 weeks now.

My Fairplay ID BF3-2018804 BF4-16558350
