### ISSUE TITLE
Multi Texts for Commands

### ISSUE THREAD

**Issue by DelilerClan** [AdKats/AdKats#861]
Feature Request: Multiple texts with comma seperated for Commands like"PRoCon Chat, GUID, Stats and Map Logger"s commands.

For example; Confirm command: yes, yeah, ok.

**Comment by ColColonCleaner** [comment]
Are there any other commands you would be interested in having multiple command texts for? 

The main issue is we want people to have a consistent experience across servers for certain commands. For example, a plugin asks you to confirm something, what do you as a player type? It's pretty much uniformly !yes, @yes, .yes, /yes, etc.

This is the reason the plugin will reject any request to change that command from the text "yes", it's so players know what to type. This was actually an issue before and the block was added because of that. Someone changed their command text for confirm to yy, so it was easier for admins, but none of the players knew that, and everyone kept trying variants of 'yes'.

**Comment by DelilerClan** [comment]
My main goal was not confirm command (I didn't even know even that cannot be changed :)). I want to have multi text for rules command. Because our location is Turkey and many of players type !kurallar or !kural to request the rules. But we have also foreign players and i dont want to change the command text. So i used insane limits to call rules command when our player type !kurallar. It is working but i am not sure what to write for source name and target name. And another request can be multilanguage rules. When our players type !kurallar Turkish written rules will be displayed. When !rules typed English written rules will be displayed. Thanks.

**Comment by Prophet731** [comment]
This sound very familiar to something someone suggested a long time ago colon. I think it was different versions of saying "yes" or "no" in different languages.
