### ISSUE TITLE
sql errors with adkats plugin running

### ISSUE THREAD

**Issue by rolltidebrad** [AdKats/AdKats#872]
You asked me to open the ticket to remind you about the issue from this link - https://forum.myrcon.com/showthread.php?6045-Advanced-In-Game-Admin-and-Ban-Enforcer-AdKats-6-8-0-0&p=131910&viewfull=1#post131910

https://forum.myrcon.com/showthread.php?6045-FREE-Advanced-In-Game-Admin-and-Ban-Enforcer-AdKats-6-9-0-0/page138&p=131864#post131864

Thanks

**Comment by ColColonCleaner** [comment]
Patching this to put nulls into the database instead of empty IP address strings when no IP exists for a player. Also adding an SQL updater to fix this across all AdKats instances.

For people who have the trigger that stops IPs from being nulled or emptied once initially entered I am using 100.100.100.100, which is currently not used anywhere.

@Prophet731 Please exclude 100.100.100.100 from matching players together by IP in your searches.

**Comment by rolltidebrad** [comment]
Great news. When will I be able to apply and test the new patch?

**Comment by ColColonCleaner** [comment]
It's updated, please grab from the test branch.

**Comment by Prophet731** [comment]
I would have set it to 127.0.0.1 since that's basicly localhost and no player would ever use that address in a public setting.

**Comment by ColColonCleaner** [comment]
@Prophet731 I'm dumb, updating it to that IP.

**Comment by rolltidebrad** [comment]
Just wanted to let you know it still crashes with the latest test branch

**Comment by Prophet731** [comment]
@ColColonCleaner 

That local IP is actually breaking the BFACP because of the linked accounts. You sure you can't leave the string blank instead?

**Comment by MECHANIC-CAT-RU** [comment]
The server was off. 
And it is is turned on now.
Sorry for my English 
--
С УВАЖЕНИЕМ, КАРИХ АЛЕКСАНДР  понедельник, 14 марта 2016г., 11:01 +03:00 от Prophet731 < notifications@github.com> :
