### ISSUE TITLE
Feature Request: Add custom battlecries for players on first spawn

### ISSUE THREAD

**Issue by wdfstryfe** [AdKats/AdKats#877]
If a user is set to "Donator" for instance they have the ability to issue the !joinmsg command to set their message when they join the game.  Maybe also a way to remove it if it contains vulgar or offensive language as well.

**Comment by ColColonCleaner** [comment]
There would need to be a way to distinguish this from the first spawn message setting that is already in AdKats. That message gets sent to every joining player, while this new message would be sent to everyone else with custom text. Perhaps it could be called the person's battlecry or herald?

Details pending input:

New commands:

battlecry msg (usable by players to set their own join announcment, defaulting to AnyHidden chat access)
setbattlecry player msg (usable by admins to set a player's join message. If nothing is passed in for msg then the player's current join message is deleted. defaulting to AnyHidden chat access.)

New settings:

Will be creating a new setting section A12-3 to hold these settings.
Player battlecry blocked words (list of strings that will case-insensitively block changes using battlecry. setbattlecry will override this setting)
Player battlecry max length (the max number of characters that a battlecry can be, defaulting to 50)
Player battlecry announcement type (say, yell, or tell. Basically controlling how loud the battlecries will be)

Behavior:

When a player first spawns in the server their set battlecry will be displayed to all players using the announcement type set. The access to these commands can be controlled like any other AdKats command. If you have the first spawn message enabled, this message will replace that message instead of being shown afterward.

Work:

This will require a new table to store battlecries, and the commands/role configuration to support it. Usually for specific things this size I charge enough for the pizza delivery and drinks i'll get while writing it, so $25-30.

**Comment by wdfstryfe** [comment]
That sounds good to me! I would use the same PayPal address as before? 
Don Williams
don@whendarknessfalls.org
Owner – WDF Gaming Network
Twitter — wdfgamingnet
Facebook — wdfgaming
YouTube — stryfetew
Website — http://whendarknessfalls.org

**Comment by ColColonCleaner** [comment]
Be careful about replying via email. It posts the entire body of the email, addresses and all. Just remember to clear out everything in the body besides what you want to post and you're fine.

**Comment by ColColonCleaner** [comment]
Request is funded. Completion should be in 1 week unless something serious comes up.

**Comment by wdfstryfe** [comment]
My guys will be excited to have this feature! Thanks again!

**Comment by ColColonCleaner** [comment]
I've been able to schedule time to get this done tomorrow night. Just got back from a trip starting late last week.

**Comment by ColColonCleaner** [comment]
Nearly completed last night but my keyboard stopped working near the end. Back to it tonight.

**Comment by wdfstryfe** [comment]
That's no bueno!  And that's fine! :)

**Comment by ColColonCleaner** [comment]
This should be completed now. Please update to the latest test version and review it.

**Comment by ColColonCleaner** [comment]
Confirmed that this was working with some admins.
