### ISSUE TITLE
REQUEST: Attack Heli K/D Limit & Kill-Limit

### ISSUE THREAD

**Issue by III-Pho3niX-III** [AdKats/AdKats#889]
HI. I would like to request a feature option in AdKats: Attack Heli K/D Limit & Kill-Limit
--------------------------------

Menu option:
1.- Set Attack Heli (Vehicles) Automatic with Infaction Randomizer Options
2.- Set K/D Limit (Attack Heli)
3.- Set Kill Limit (Attack Heli)
4.- Set Actions: How many warning (enable/disable), Kill Action (enable/disable), Kick  Action (enable/disable), Temp-Ban (enable/disable)

This keep the server balanced for Farmers/Rapers

Thanks in advance!

Cheers.

**Comment by hit757** [comment]
What about people who are extraordinary in other vehicles or even on foot?
Maybe you just need K/D ratio limit on join to filter them out? :)

**Comment by III-Pho3niX-III** [comment]
This is only for the Attack Heli on CQL Maps. We dont want that the server get raped by these pilots. If the server get raped/owned players will leave the server. K/D Limit and Kill Limit will set in AdKats this is just a request if this is possible.

**Comment by ColColonCleaner** [comment]
This is currently possible in insane limits, and i believe there is already a script for this, but i'm not sure if it's vehicle specific.

I'd rather not be including autoadmin actions like this in AdKats, since it's not an anti-cheat measure or a server config. Sorry. I would suggest looking for an IL script for this.
