### ISSUE TITLE
adkats not working due to mysql connection failing. Have to run mysqladmin flush-hosts to clear up

### ISSUE THREAD

**Issue by mikedevita** [AdKats/AdKats#891]
like the extra long title says, running latest adkats every once in awhile adkats decides to break and i have to run `mysqladmin flush-hosts -p` on the db server. It seems the procon hosts IP gets blocked for some reason. Not sure why it keeps happening though, or if this is even an adkats issue at all.

**Comment by ColColonCleaner** [comment]
Run the below commands on your MySQL DB:

SET GLOBAL max_connect_errors = 10000;
SET  GLOBAL max_connections = 200;

Then check the vars to make sure the change went through:

show variables like "max_connections";
show variables like "max_connect_errors";

Sometimes when attacks happen or a DB is under load errors can be thrown on connection to the DB. This can very quickly cause AdKats to hit your connect error limit since it issues between 40-80 queries per minute depending on your server load. AdKats handles DB disconnect/errors but that doesn't stop the DB itself from rejecting connections after a time of bad connection. We've had to make the same types of changes to our systems. You shouldn't see any issues after updating your vars.

**Comment by mikedevita** [comment]
thanks for the detailed response, I've also gone ahead and initiated iptables to drop all connections that arent from the procon IP.
