### ISSUE TITLE
Kick on missing ping

### ISSUE THREAD

**Issue by ChaT0n** [AdKats/AdKats#921]
Not the first time I am noticing this, but players with no ping are able to play an entire round on the server, even when the missing ping kick is activated.

I don't know if adkats consider the missing ping's value as 0 or as -1 like the procon layer.

Thanks

PS: also the attempt to fix the missing ping is activated. Maybe I should try it while it is disabled.

**Comment by ColColonCleaner** [comment]
@ChaT0n Do you have the manual ping when missing option enabled?

**Comment by ChaT0n** [comment]
Oups, thought i've answered that one: yes missing ping kick is enabled

**Comment by ColColonCleaner** [comment]
Ok, then it would seem your layer is able to ping them by IP even though the game server is not. Use the pinfo command on them to check what their ping is.

If the layer is able to get their ping, and that ping it gets is under the limit, then it allows them to continue playing. If you want it to kick them anyway even if the layer is able to get their ping (since players can't see it), then just turn off the manual ping when missing option.
