### ISSUE TITLE
Question around AdKats Anti-Cheat systems

### ISSUE THREAD

**Issue by deluxesss** [AdKats/AdKats#972]
People get auto-banned although I switched off anti cheat. I did this because I was banned on my own server and now I don't trust in that feature anymore. Please tell me how to switch this off. Thanks for your help.

Greetings

**Comment by ColColonCleaner** [comment]
Please post the ban reason for which you were banned.

**Comment by ColColonCleaner** [comment]
@deluxesss Please respond.

**Comment by deluxesss** [comment]
Thanks for the quick response. Unfortenetly I can't remember if it was DPS, HSK or KPM because it happened some month ago. Something usual like "DPS Automatic Ban [4-AUGA3-52-61-4-116]". Is it possible to add the player name in ban reason of DPS checker ? I guess it is not off-switcheable ?

**Comment by ColColonCleaner** [comment]
Run this on your database to get the information about your ban. assuming your name was deluxxesss at the time, if not just modify that text below.

select source_name, record_message from adkats_records_main where target_name = 'deluxesss' and command_action = 8

Yes a lot of the reason messages may seem the same but knowing why yours was suspicious is what's important here.

**Comment by ColColonCleaner** [comment]
And no, currently this functionality cannot be disabled. It used to be optional but that was removed after years of testing with no false positives caused by plugin issues. This is why a false positive of this nature is shocking to me, and why I need your ban message.
If there is truly a plugin issue then i need to either provide an option to disable it again, or find out what calculation problem is causing this.

**Comment by ColColonCleaner** [comment]
Also, do you run a normal or a hardcore server?

**Comment by deluxesss** [comment]
Thanks for the quick response. Unfortenetly I can't remember if it was DPS, HSK or KPM because it happened some month ago. Something usual like "DPS Automatic Ban [4-AUGA3-52-61-4-116]". Is it possible to add the player name in ban reason of DPS checker ? I guess it is not off-switcheable ?

**Comment by ColColonCleaner** [comment]
This is the same comment you made yesterday. Please follow what I mentioned above to fetch the ban reason, it's in your database.

**Comment by deluxesss** [comment]
*yeah just pushed enter and the text was still in ^^°

The preset is "normal". Unfortenetly there was nor result after entering the code in my database. To be sure I've testet it with a banned name. Possibly it happended before changing my gamecloud :/ . I guess it was not a DPS ban if you say after years of testing. Would it be possible to display the banned player name in ban reason or ban him by pb GUID so I can see who it is ? OR do I need to check the database for the name or use the ban enforcer by name ?

Thanks for your help

**Comment by ColColonCleaner** [comment]
One of the reasons i made the ban enforcer was because there was no way with the default battlefield ban list to include a player name without adding it to the ban reason. They aren't banned because of their name so it didn't make sense to include that in the ban reason.

If you're running the BFAdminCP by Prophet731 you are able to look at a player's profile and see all their previous bans and active ban if they have one. And if you don't have that, the name of the player being banned is always included in the ban record, even though it's not in the ban reason itself. Would you like me to post a query that will show the latest 100 bans along with the date, player name, and banning admin name?

AdKats does not currently do any bans via PB info, or interact with the PB functionality in any way aside from triggering screenshots on reported players.

My level of confidence with the DPS triggers is extremely high. It's been tested across 3000+ servers and millions of unique players for years now. That is why there is no option to turn it off. If it thinks a player should be banned, they should be banned. Feel free to disable the other sections if you want to though, as those are more by admin discretion than anything else, especially the KPM triggers.

**Comment by deluxesss** [comment]
I understand your point of view and it's okay for 99% of the servers but I would like to check the banned people to see if there is someone between I know. There is one guy for example who has more than 30 accounts banned on my server because he is obviously cheating. Always low level accounts 99% cheat o meter. I check those people by shared IP addresses, report screenshots to ACI & GGC and wihout a name I can't re-check them. I will try BFAdminCP, thanks for the hint. Looks more comforteable than searching in database tables :) . 

I use three ban lists ^^ but I guess you're talking about the adkats ban list ? But in this table is no reason, playername etc shown but I'm a database noob and maybe you can tell me what exactly you are talking about. Where you want me to send it to ?

**Comment by Prophet731** [comment]
Here is the query to view the banlist in the database. It has the basic info you need.

```SQL
SELECT 
    adkats_bans.ban_id,
    tbl_playerdata.SoldierName,
    adkats_bans.ban_startTime,
    adkats_bans.ban_endTime,
    adkats_bans.ban_status,
    adkats_records_main.record_message
FROM
    adkats_bans
        INNER JOIN
    tbl_playerdata ON tbl_playerdata.PlayerID = adkats_bans.player_id
        INNER JOIN
    adkats_records_main ON adkats_bans.latest_record_id = adkats_records_main.record_id
ORDER BY adkats_bans.ban_startTime DESC
LIMIT 100
```

**Comment by ColColonCleaner** [comment]
Remember how you ran that query before to check what your ban reason was? This is the same type of thing but will show you the names and ban reasons for the last 100 banned players. If you want everyone, just delete the 'limit 100' line at the end. It's a relatively simple query but it should give you what you are looking for if you don't end up installing the BFAdminCP.
`
  select tpd.SoldierName as PlayerName,
         tpd.EAGUID as PlayerGUID,
         tpd.IP_Address as PlayerIP,
         arm.record_message as BanReason,
         arm.source_name as BanningAdmin,
         ab.ban_startTime as StartDate,
         ab.ban_endTime as EndDate,
         ab.ban_enforceName as NameEnforce,
         ab.ban_enforceGUID as GUIDEnforce,
         ab.ban_enforceIP as IPEnforce
    from adkats_bans ab
    join adkats_records_main arm
      on ab.player_id = arm.target_id
    join tbl_playerdata tpd
      on ab.player_id = tpd.PlayerID
   where ab.ban_status = "Active"
order by ab.ban_startTime desc
   limit 100
`

**Comment by ColColonCleaner** [comment]
@Prophet731 lol just realized you commented as well.

**Comment by deluxesss** [comment]
Okay I finally got that you offered me to send that query and not asking me to send you my latest 100 bans x) . Thank you guys very much :) ! That's way easier than searching in different tables to find out some more about bans :D.

**Comment by ColColonCleaner** [comment]
Glad the queries are working for you. If you have any more questions around the anti-cheat systems or banning please let us know, otherwise i'll close this issue.

**Comment by Prophet731** [comment]
@ColColonCleaner You slow :P

**Comment by deluxesss** [comment]
Fully pleased, thx a lot :)

**Comment by ColColonCleaner** [comment]
@deluxesss Even though this is closed I'm interested in a couple other things.

Do you have the LIVE system enabled? This section of the script allows the DPS checker to catch damage mods after 1 round of play, instead of using overall stats. If you don't have that enabled, i would suggest at least turning that on. It won't act on HSK or KPM based metrics if you have those sections disabled.

Secondly, why so many ban lists? You mentioned 3 of them, why keep them separate?

**Comment by ColColonCleaner** [comment]
@deluxesss 

Just realized my query would give you the wrong information for ban reason/admin. Typo. Fixed.

```SQL
  select tpd.SoldierName as PlayerName,
         tpd.EAGUID as PlayerGUID,
         tpd.IP_Address as PlayerIP,
         arm.record_message as BanReason,
         arm.source_name as BanningAdmin,
         ab.ban_startTime as StartDate,
         ab.ban_endTime as EndDate,
         ab.ban_enforceName as NameEnforce,
         ab.ban_enforceGUID as GUIDEnforce,
         ab.ban_enforceIP as IPEnforce
    from adkats_bans ab
    join adkats_records_main arm
      on ab.latest_record_id = arm.record_id
    join tbl_playerdata tpd
      on ab.player_id = tpd.PlayerID
   where ab.ban_status = "Active"
order by ab.ban_startTime desc
   limit 100
```
