### ISSUE TITLE
Add users

### ISSUE THREAD

**Issue by hemaniaco** [AdKats/AdKats#973]
Good afternoon,

Im facing a new issue.
Manage to add a user (Full Admin) User Expiration/Notes/Role/Delete User/Add Soldier/ Soldier | 1 | BF4 |

Ive checked on the server and all commands work.
Here comes my problem, If I try to add more users, I dont get the final sentence:

USRx | Nickname | Soldiers | etc....

I can add as much as I want but it looks like i can not add them properly.
I have to say that is the first time i try to start a server after following instructions.

Thanks in advance for the help
![bf4](https://user-images.githubusercontent.com/35308004/34789643-55bccab8-f63f-11e7-8767-8931ff9b8e1d.jpg)

**Comment by ColColonCleaner** [comment]
@hemaniaco I don't know why I didn't notice this before. Apologies for the delay.

This is because those players were not in your system yet when you loaded their users. To load a player onto a user they need to have joined the server at least once after AdKats was installed so we have an ID for them. 

After they join the server at least once please enter their name into the 'Add Soldier' field for the respective user and it will add them to it.

**Comment by ColColonCleaner** [comment]
Closing as expired.
