### ISSUE TITLE
Warnings about report/calladmin command weights.

### ISSUE THREAD

**Issue by onczopek** [AdKats/AdKats#982]
[07:04:25 09] [AdKats] WARNING: Unable to find target weight for command 18|61

**Comment by ColColonCleaner** [comment]
Run these commands on your database:

update adkats_records_main set command_action = 62 where command_action = 61 and command_type in (18, 20);
update adkats_records_main set command_action = 42 where command_action = 41 and command_type in (18, 20);

**Comment by onczopek** [comment]
ColColonCleaner very thank you working that command for me, but have next warrning
 WARNING: Unable to find source weight for command 18|40, you will help me with this. MySQL database is unfortunately a difficult topic for me and I cannot deal with the problem myself.

**Comment by ColColonCleaner** [comment]
@onczopek Don't worry about it, it's not your fault, i'm here to help.

I updated my previous answer with another query to run. I will be adding these into the base AdKats plugin so that they are fixed automatically. But, for now, run the following when you see these.

update adkats_records_main set command_action = 62 where command_action = 61 and command_type in (18, 20);
update adkats_records_main set command_action = 42 where command_action = 41 and command_type in (18, 20);
update adkats_records_main set command_action = 19 where command_action = 40 and command_type in (18, 20);

**Comment by ColColonCleaner** [comment]
Assigned myself. Will be adding a section to automatically fix these when they come up.

**Comment by ColColonCleaner** [comment]
Added this. will be in the next test version.

**Comment by onczopek** [comment]
Welcome, I apologize that only now I was able to call you back, thank you very much because your solusions helped me and I have no previous warnings left only one warrning - mistake. [AdKats] WARNING: Unable to find target weight for command 18|40

**Comment by ColColonCleaner** [comment]
@onczopek Try updating to the latest test version with /pupdate, let me know if you still see the issues then. I added code to automatically fix these now, should be working.

**Comment by onczopek** [comment]
Yes i update adkats and now no see any warrning, If there would be a possibility for you to contact me privately, I would have an order to you for a fee, thank you.

**Comment by ColColonCleaner** [comment]
You mean making a donation? There is a donation link in the main AdKats forum thread, at the bottom.
https://forum.myrcon.com/showthread.php?6045-FREE-Advanced-In-Game-Admin-and-Ban-Enforcer-AdKats-7-0-1-0
Thanks man :+1:
