### ISSUE TITLE
Bans gone out of procon

### ISSUE THREAD

**Issue by dangerBEclose** [AdKats/AdKats#995]
Hello, How can I restore all the bans in procon?
AdKats has removed them all.
Thanks

**Comment by ColColonCleaner** [comment]
AdKats has not removed the bans, it has imported them into your database because you turned the ban enforcer on. Please read up on how the ban enforcer operates.

https://github.com/AdKats/AdKats#ban-enforcer

**Comment by dangerORclose** [comment]
Okay thanks! I did not found that :D
So if I understand it correctly, this happened because someone did enable the ban enforcer option? It was not enabled by default? And when I will disable that function it will put the bans back, but not the reasons?

Hope you can answer these two questions, thanks :)

**Comment by ColColonCleaner** [comment]
Correct. The ban enforcer is not enabled by default because listing your bans and seeing recent bans is more difficult if you don't have the BFAdminCP installed. However, there is a mini ban management section of the AdKats settings where you can search for players by name to list their bans and manage them that way. Also with it enabled you have access to the /unban command from in game, so you can manage bans without opening procon.

If you only have one server and only care about enforcing bans on one metric you can likely just have procon manage it. Unless you have more than a few thousand bans in which case procon gets very slow. My group had around 40,000 active bans across our 12 servers during the height of bf3/bf4, so procon was very slow, one of the reasons i built the ban enforcer.

When you import your bans back into procon they will be against the original enforcement type (eaguid, ip, or name). The bans will still be in your database after the re-import, just won't be updated or acted on.

**Comment by ColColonCleaner** [comment]
Make sure you do not shut down procon or the game server until the re-import is finished. Progress messages are printed in the plugin console during the import. It is not an instant process. It will take some time depending on how many bans you have.

**Comment by dangerORclose** [comment]
Okay, thank you a lot for your time and effort explaining and providing the info to me!
__

**Comment by dangerBEclose** [comment]
Hey, I have got the server wish runs out MySql online again.
Wasn't able to do this fix until now. I have done as you told, disable the ban enforcer option, wish was disabled. So I enabled it, waited for it to upload the bans, then I disabled it. It says downloading and after that repopulating procon banlist.
But the bans are not there in procon. At least I don't see them. Why is this? Does it require a Procon layer reboot? Thanks in advance.

**Comment by ColColonCleaner** [comment]
I believe there is a refresh button on the procon UI. Try clicking that. If it said it was repopulating the procon ban list and you got the message "All AdKats Enforced bans repopulated to procon's ban list." then the process completed successfully.

**Comment by dangerBEclose** [comment]
Hey, this is what I see.
https://pastebin.com/CYKxs8eQ
But the bans are not added. I clicked that button, nothing, I restarted procon, nothing. Even after restarting the procon layer itself.

**Comment by ColColonCleaner** [comment]
So with the ban enforcer now off, try banning yourself. Do you see a ban for your player in the banlist?

**Comment by dangerBEclose** [comment]
It gets  added to the Procon banlist yes.
If you want you can meet me on a ts3 server for faster communication.
Can send ip if you agree.

**Comment by ColColonCleaner** [comment]
Yeah. I'm curious about whether this still works properly.

**Comment by dangerBEclose** [comment]
Poke me when you joined, dangerBEclose, you won't be able to move yourself directly to a channel.

**Comment by dangerBEclose** [comment]
Okay, we don't match time probably it is mid night for me.
Then I won't be on pc anymore hmm but anyway the bans are not showing. Hope this can get fixed. Otherwise I lost over 700 bans.

**Comment by ColColonCleaner** [comment]
In the meantime i would suggest you leave the ban enforcer active. It will still enforce those bans and any new bans you add will be automatically downloaded. We can set up a time to meet and experiment with a solution.

**Comment by dangerBEclose** [comment]
Okay, I have time now for the next 4 hours. In case you can.

**Comment by ColColonCleaner** [comment]
It will probably be this weekend. I can join any time tomorrow or the next day.

**Comment by dangerBEclose** [comment]
Okay cool just message me tomorrow when you are available! Thank you

**Comment by dangerBEclose** [comment]
Okay, I can't now. That will be over 4 or 5 hours from now before I can come on pc.
However we have lost our MySql data so we won't be able to do much since it is gone now. Forever.. Unless it is stored on Procon? It said downloading and repopulating. Maybe it downloaded it under a diffrent name? No idea, that would be my last hope. MySql db got wiped.. ~dangerBEclose

**Comment by ColColonCleaner** [comment]
Did you have any procon backups? Any MySQL backups?

**Comment by ColColonCleaner** [comment]
I'll sit in the teamspeak for the rest of the day. Just poke me when you come back online.

**Comment by dangerBEclose** [comment]
Maybe old procon one but verrry old so lets take that as a no. And for MySql there os totaly no backup. We were in setup fase. But something went wrong resulting in a snapshot restore. So it is gone. No way back.

**Comment by ColColonCleaner** [comment]
I'm very sorry to hear that. Unfortunately there is nothing I can do if the data was completely lost due to no backups being taken. Maybe talk with your DB host to see if they have any incremental backups, unless you've already tried that. Having a database be corrupted really isn't a use case plugins can code around.
Even if your ban list in the database somehow got destroyed but the records table was still there i could reconstruct the bans based on that records list, since it creates a ban record for each ban it downloads. But if the database is completely gone there is nothing I can do.

**Comment by dangerBEclose** [comment]
It is self hosted, so there is no backup from external party. Thanks anyway for your help!
If you are interested to play games with us feel free to join teamspeak at any time!
We play a bunch of games, but mostly Battlefield, pubg, wow, wot, and much much more.
You may close this 👍
